/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gc_david_dfm_Haversine */

#ifndef _Included_gc_david_dfm_Haversine
#define _Included_gc_david_dfm_Haversine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gc_david_dfm_Haversine
 * Method:    getDistanceJNI
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_gc_david_dfm_Haversine_getDistanceJNI
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
