package gc.david.dfm.model.v2;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import gc.david.dfm.model.v2.Distance;
import gc.david.dfm.model.v2.Position;

import gc.david.dfm.model.v2.DistanceDao;
import gc.david.dfm.model.v2.PositionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig distanceDaoConfig;
    private final DaoConfig positionDaoConfig;

    private final DistanceDao distanceDao;
    private final PositionDao positionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        distanceDaoConfig = daoConfigMap.get(DistanceDao.class).clone();
        distanceDaoConfig.initIdentityScope(type);

        positionDaoConfig = daoConfigMap.get(PositionDao.class).clone();
        positionDaoConfig.initIdentityScope(type);

        distanceDao = new DistanceDao(distanceDaoConfig, this);
        positionDao = new PositionDao(positionDaoConfig, this);

        registerDao(Distance.class, distanceDao);
        registerDao(Position.class, positionDao);
    }
    
    public void clear() {
        distanceDaoConfig.getIdentityScope().clear();
        positionDaoConfig.getIdentityScope().clear();
    }

    public DistanceDao getDistanceDao() {
        return distanceDao;
    }

    public PositionDao getPositionDao() {
        return positionDao;
    }

}
