[versions]
# SDK versions
minSdk = "23"
targetSdk = "35"
compileSdk = "36"

# App version
appVersionCode = "30"
appVersionName = "3.5"

# Library versions
activityKtx = "1.9.3"
archCompTesting = "2.2.0"
cardView = "1.0.0"
collectionKtx = "1.5.0"
constraintLayout = "2.2.1"
coreKtx = "1.17.0"
coroutines = "1.10.2"
coroutinesTest = "1.10.2"
crashlytics = "19.4.4"
crashlyticsPlugin = "3.0.2"
googleServices = "4.4.4"
gradle = "8.13.2"
graphview = "4.2.2"
gson = "2.13.2"
junit = "4.13.2"
koin = "3.1.4"
kotlin = "2.3.10"
ksp = "2.3.6"
leakCanary = "2.14"
lifecycle = "2.10.0"
lottie = "5.2.0"
materialComponents = "1.13.0"
mockito = "5.22.0"
mockitoKotlin = "5.4.0"
okhttp = "4.12.0"
playReview = "2.0.2"
playServicesLocation = "21.3.0"
playServicesMaps = "19.0.0"
preference = "1.2.1"
room = "2.8.4"
timber = "5.0.1"

[libraries]
# Regular dependencies
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardView" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "collectionKtx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "crashlytics" }
graphview = { module = "com.jjoe64:graphview", version.ref = "graphview" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material-components = { module = "com.google.android.material:material", version.ref = "materialComponents" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-review = { module = "com.google.android.play:review", version.ref = "playReview"}
playservices-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
playservices-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Test dependencies
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "archCompTesting" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room"}
