package gc.david.dfm.model.v1;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import gc.david.dfm.model.v1.Entry;

import gc.david.dfm.model.v1.EntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entryDaoConfig;

    private final EntryDao entryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entryDaoConfig = daoConfigMap.get(EntryDao.class).clone();
        entryDaoConfig.initIdentityScope(type);

        entryDao = new EntryDao(entryDaoConfig, this);

        registerDao(Entry.class, entryDao);
    }
    
    public void clear() {
        entryDaoConfig.clearIdentityScope();
    }

    public EntryDao getEntryDao() {
        return entryDao;
    }

}
