package gc.david.dfm.model.v1;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import gc.david.dfm.model.v1.Entry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTRY.
*/
public class EntryDao extends AbstractDao<Entry, Long> {

    public static final String TABLENAME = "ENTRY";

    /**
     * Properties of entity Entry.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property Lat_origen = new Property(2, double.class, "lat_origen", false, "LAT_ORIGEN");
        public final static Property Lon_origen = new Property(3, double.class, "lon_origen", false, "LON_ORIGEN");
        public final static Property Lat_destino = new Property(4, double.class, "lat_destino", false, "LAT_DESTINO");
        public final static Property Lon_destino = new Property(5, double.class, "lon_destino", false, "LON_DESTINO");
        public final static Property Distancia = new Property(6, String.class, "distancia", false, "DISTANCIA");
        public final static Property Fecha = new Property(7, String.class, "fecha", false, "FECHA");
    };


    public EntryDao(DaoConfig config) {
        super(config);
    }
    
    public EntryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTRY' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'NOMBRE' TEXT NOT NULL ," + // 1: nombre
                "'LAT_ORIGEN' REAL NOT NULL ," + // 2: lat_origen
                "'LON_ORIGEN' REAL NOT NULL ," + // 3: lon_origen
                "'LAT_DESTINO' REAL NOT NULL ," + // 4: lat_destino
                "'LON_DESTINO' REAL NOT NULL ," + // 5: lon_destino
                "'DISTANCIA' TEXT NOT NULL ," + // 6: distancia
                "'FECHA' TEXT NOT NULL );"); // 7: fecha
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTRY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Entry entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
        stmt.bindDouble(3, entity.getLat_origen());
        stmt.bindDouble(4, entity.getLon_origen());
        stmt.bindDouble(5, entity.getLat_destino());
        stmt.bindDouble(6, entity.getLon_destino());
        stmt.bindString(7, entity.getDistancia());
        stmt.bindString(8, entity.getFecha());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Entry readEntity(Cursor cursor, int offset) {
        Entry entity = new Entry( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nombre
            cursor.getDouble(offset + 2), // lat_origen
            cursor.getDouble(offset + 3), // lon_origen
            cursor.getDouble(offset + 4), // lat_destino
            cursor.getDouble(offset + 5), // lon_destino
            cursor.getString(offset + 6), // distancia
            cursor.getString(offset + 7) // fecha
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Entry entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.getString(offset + 1));
        entity.setLat_origen(cursor.getDouble(offset + 2));
        entity.setLon_origen(cursor.getDouble(offset + 3));
        entity.setLat_destino(cursor.getDouble(offset + 4));
        entity.setLon_destino(cursor.getDouble(offset + 5));
        entity.setDistancia(cursor.getString(offset + 6));
        entity.setFecha(cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Entry entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Entry entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
