/*
 * Copyright (c) 2018 David Aguiar Gonzalez
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gc.david.dfm.model.v1;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ENTRY".
 */
@Entity
public class Entry {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String nombre;
    private double lat_origen;
    private double lon_origen;
    private double lat_destino;
    private double lon_destino;

    @NotNull
    private String distancia;

    @NotNull
    private String fecha;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Entry() {
    }

    public Entry(Long id) {
        this.id = id;
    }

    @Generated
    public Entry(Long id, String nombre, double lat_origen, double lon_origen, double lat_destino, double lon_destino, String distancia, String fecha) {
        this.id = id;
        this.nombre = nombre;
        this.lat_origen = lat_origen;
        this.lon_origen = lon_origen;
        this.lat_destino = lat_destino;
        this.lon_destino = lon_destino;
        this.distancia = distancia;
        this.fecha = fecha;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(@NotNull String nombre) {
        this.nombre = nombre;
    }

    public double getLat_origen() {
        return lat_origen;
    }

    public void setLat_origen(double lat_origen) {
        this.lat_origen = lat_origen;
    }

    public double getLon_origen() {
        return lon_origen;
    }

    public void setLon_origen(double lon_origen) {
        this.lon_origen = lon_origen;
    }

    public double getLat_destino() {
        return lat_destino;
    }

    public void setLat_destino(double lat_destino) {
        this.lat_destino = lat_destino;
    }

    public double getLon_destino() {
        return lon_destino;
    }

    public void setLon_destino(double lon_destino) {
        this.lon_destino = lon_destino;
    }

    @NotNull
    public String getDistancia() {
        return distancia;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDistancia(@NotNull String distancia) {
        this.distancia = distancia;
    }

    @NotNull
    public String getFecha() {
        return fecha;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha(@NotNull String fecha) {
        this.fecha = fecha;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
