package gc.david.dfm.model.v1;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ENTRY.
 */
public class Entry {

    private Long id;
    /** Not-null value. */
    private String nombre;
    private double lat_origen;
    private double lon_origen;
    private double lat_destino;
    private double lon_destino;
    /** Not-null value. */
    private String distancia;
    /** Not-null value. */
    private String fecha;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Entry() {
    }

    public Entry(Long id) {
        this.id = id;
    }

    public Entry(Long id, String nombre, double lat_origen, double lon_origen, double lat_destino, double lon_destino, String distancia, String fecha) {
        this.id = id;
        this.nombre = nombre;
        this.lat_origen = lat_origen;
        this.lon_origen = lon_origen;
        this.lat_destino = lat_destino;
        this.lon_destino = lon_destino;
        this.distancia = distancia;
        this.fecha = fecha;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public double getLat_origen() {
        return lat_origen;
    }

    public void setLat_origen(double lat_origen) {
        this.lat_origen = lat_origen;
    }

    public double getLon_origen() {
        return lon_origen;
    }

    public void setLon_origen(double lon_origen) {
        this.lon_origen = lon_origen;
    }

    public double getLat_destino() {
        return lat_destino;
    }

    public void setLat_destino(double lat_destino) {
        this.lat_destino = lat_destino;
    }

    public double getLon_destino() {
        return lon_destino;
    }

    public void setLon_destino(double lon_destino) {
        this.lon_destino = lon_destino;
    }

    /** Not-null value. */
    public String getDistancia() {
        return distancia;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDistancia(String distancia) {
        this.distancia = distancia;
    }

    /** Not-null value. */
    public String getFecha() {
        return fecha;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
