package gc.david.dfm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table POSITION.
 */
public class Position {

    private Long id;
    private double latitude;
    private double longitude;
    private long distanceId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Position() {
    }

    public Position(Long id) {
        this.id = id;
    }

    public Position(Long id, double latitude, double longitude, long distanceId) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.distanceId = distanceId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public long getDistanceId() {
        return distanceId;
    }

    public void setDistanceId(long distanceId) {
        this.distanceId = distanceId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
